version: '3.8'

services:
  postgres:
    image: postgres:14.17
    environment:
      POSTGRES_DB: MicroServcesDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: leamon2004
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservice-network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8755:8755"
    networks:
      - microservice-network
    depends_on:
      - postgres

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/MicroServcesDB
      - DB_USERNAME=postgres
      - DB_PASSWORD=leamon2004
      - EUREKA_URL=http://eureka-server:8755/eureka/
    networks:
      - microservice-network
    depends_on:
      - postgres
      - eureka-server

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/MicroServcesDB
      - DB_USERNAME=postgres
      - DB_PASSWORD=leamon2004
      - EUREKA_URL=http://eureka-server:8755/eureka/
    networks:
      - microservice-network
    depends_on:
      - postgres
      - eureka-server

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8756:8756"
    environment:
      - EUREKA_URL=http://eureka-server:8755/eureka/
    networks:
      - microservice-network
    depends_on:
      - eureka-server
volumes:
  postgres-data:

networks:
  microservice-network:
    driver: bridge